default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: binder
  password:

development:
  <<: *default
  database: binder_development

test:
  <<: *default
  database: binder_test

production:
  <<: *default
  database: binder_production
